theme: jekyll-theme-slate
title: trenza.bi
description: Business Intelligence by Momentis
logo: /assets/img/trenza-signature-icon-blue.png
show_downloads: false
markdown: kramdown
github:
  is_project_page: false